on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    # Runs a single command using the runners shell
    - name: Ls
      run: ls -la    
  
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can have access to it
    - name: Git Clone
      uses: actions/checkout@v4
      with:
        ref: 'master'
        
    # Runs a single command using the runners shell
    - name: Ls
      run: ls -la
      
    # Install composer
    - name: Install composer dependencies
      run: composer install --no-scripts

    # PHPUnit tests
    - name: PHPUnit tests
      run: php artisan test

# This workflow contains a single job called "web-deploy"
  ssh-git-pull:
    name: ssh-git-pull
    runs-on: ubuntu-latest
    needs: [web-deploy]
    steps:
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.printshopeld.com
          username: Abel@print.printshopeld.com
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/phptelebot/