on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    # Runs a single command using the runners shell
    - name: Ls
      run: ls -la    
  
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can have access to it
    - name: Git Clone
      uses: actions/checkout@v4
      with:
        ref: 'master'
        
    # Runs a single command using the runners shell
    - name: Ls
      run: ls -la

    # Install composer
    - name: Install composer dependencies
      run: composer install --no-scripts 

    # PHPUnit tests
    - name: PHPUnit tests
      run: php artisan test
    
    # configure php
    - name: Setup PHP Action
      uses: shivammathur/setup-php@2.30.4
      with:
        php-version: '8.3'
        extensions: imagick, swoole, openssl

    # create deploymet archive
    - name: Create deployment archive
      env: 
        GITHUB_SHA: ${{ github.sha }}
      run: tar -czf *${GITHUB_SHA}*.tar.gz --exclude=*.git --exclude=node_modules *

    # store artifacts for distribution
    - name: store artifacts for distribution
      uses: nanoufo/action-upload-artifacts-and-release-assets@v2
      with:
        name: app-build
        path: ${{ github.sha}}.tar.gz

# This workflow contains a single job called "web-deploy"
  # ssh-git-pull:
  #   name: ssh-git-pull
  #   runs-on: ubuntu-latest
  #   needs: [web-deploy]
  #   steps:
  #     - name: executing remote ssh commands using password
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.SSH_SITES_IP }}
  #         username: ${{ secrets.FTP_SITES_USER }}
  #         password: ${{ secrets.FTP_SITES_PASSWORD }}
  #         port: ${{ secrets.SSH_SITES_PORT }}
  #         script: |
  #           cd www/print.printshopeld.com
  #           git pull
  #           exit