on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    # Runs a single command using the runners shell
    - name: Ls
      run: ls -la    
  
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can have access to it
    - name: Git Clone
      uses: actions/checkout@v4
      with:
        ref: 'master'
        
    # Runs a single command using the runners shell
    - name: Ls
      run: ls -la

    # Install composer
    - name: Install composer dependencies
      run: composer install --no-scripts 

    # PHPUnit tests
    - name: PHPUnit tests
      run: php artisan test
    
    # configure php
    - name: Setup PHP Action
      uses: shivammathur/setup-php@2.30.4
      with:
        php-version: '8.3'
        extensions: imagick, swoole, openssl

    # create deploymet archive
    - name: Create deployment archive
      env: 
        GITHUB_SHA: ${{ github.sha }}
      run: tar -czf "${GITHUB_SHA}".tar.gz --exclude=*.git --exclude=node_modules *

    # store artifacts for distribution
    - name: store artifacts for distribution
      uses: actions/upload-artifact@v4
      with:
        name: app-build
        path: ${{ github.sha}}.tar.gz

# Prepairing release on server
  ssh-release:
    name: ssh-release
    runs-on: ubuntu-latest
    needs: [web-deploy]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-build
      - name: upload
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_SITES_IP }}
          username: ${{ secrets.FTP_SITES_USER }}
          password: ${{ secrets.FTP_SITES_PASSWORD }}
          port: ${{ secrets.SSH_SITES_PORT }}
          source: ${{ github.sha}}.tar.gz
          target: /home/printsh1/print.printshopeld.com/artifacts
      - name: extract archive and create directory
        uses: appleboy/ssh-action@master
        env: 
          GITHUB_SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.SSH_SITES_IP }}
          username: ${{ secrets.FTP_SITES_USER }}
          password: ${{ secrets.FTP_SITES_PASSWORD }}
          port: ${{ secrets.SSH_SITES_PORT }}
          envs: GITHUB_SHA
          script: |
            mkdir -p "/home/printsh1/print.printshopeld.com/release/${GITHUB_SHA}"
            tar xzf /home/printsh1/print.printshopeld.com/artifacts/${GITHUB_SHA}.tar.gz -c "/home/printsh1/print.printshopeld.com/release/${GITHUB_SHA}"
            